moneda_index:
    path:     /
    defaults: { _controller: "PylifeBundle:PlMoneda:index" }
    methods:  GET

moneda_show:
    path:     /{id}/show
    defaults: { _controller: "PylifeBundle:PlMoneda:show" }
    methods:  GET

moneda_new:
    path:     /new
    defaults: { _controller: "PylifeBundle:PlMoneda:new" }
    methods:  [GET, POST]

moneda_edit:
    path:     /{id}/edit
    defaults: { _controller: "PylifeBundle:PlMoneda:edit" }
    methods:  [GET, POST]

moneda_delete:
    path:     /{id}/delete
    defaults: { _controller: "PylifeBundle:PlMoneda:delete" }
    methods:  DELETE
