periopre_index:
    path:     /
    defaults: { _controller: "PylifeBundle:PlPeriodoPremio:index" }
    methods:  GET

periopre_show:
    path:     /{id}/show
    defaults: { _controller: "PylifeBundle:PlPeriodoPremio:show" }
    methods:  GET

periopre_new:
    path:     /new
    defaults: { _controller: "PylifeBundle:PlPeriodoPremio:new" }
    methods:  [GET, POST]

periopre_edit:
    path:     /{id}/edit
    defaults: { _controller: "PylifeBundle:PlPeriodoPremio:edit" }
    methods:  [GET, POST]

periopre_delete:
    path:     /{id}/delete
    defaults: { _controller: "PylifeBundle:PlPeriodoPremio:delete" }
    methods:  DELETE
