producto_index:
    path:     /
    defaults: { _controller: "PylifeBundle:PlProducto:index" }
    methods:  GET

producto_show:
    path:     /{id}/show
    defaults: { _controller: "PylifeBundle:PlProducto:show" }
    methods:  GET

producto_new:
    path:     /new
    defaults: { _controller: "PylifeBundle:PlProducto:new" }
    methods:  [GET, POST]

producto_edit:
    path:     /{id}/edit
    defaults: { _controller: "PylifeBundle:PlProducto:edit" }
    methods:  [GET, POST]

producto_delete:
    path:     /{id}/delete
    defaults: { _controller: "PylifeBundle:PlProducto:delete" }
    methods:  DELETE
