premio_index:
    path:     /
    defaults: { _controller: "PylifeBundle:PlPremio:index" }
    methods:  GET

premio_show:
    path:     /{id}/show
    defaults: { _controller: "PylifeBundle:PlPremio:show" }
    methods:  GET

premio_new:
    path:     /new
    defaults: { _controller: "PylifeBundle:PlPremio:new" }
    methods:  [GET, POST]

premio_edit:
    path:     /{id}/edit
    defaults: { _controller: "PylifeBundle:PlPremio:edit" }
    methods:  [GET, POST]

premio_delete:
    path:     /{id}/delete
    defaults: { _controller: "PylifeBundle:PlPremio:delete" }
    methods:  DELETE
