roles_index:
    path:     /
    defaults: { _controller: "PylifeBundle:PlRole:index" }
    methods:  GET

roles_show:
    path:     /{id}/show
    defaults: { _controller: "PylifeBundle:PlRole:show" }
    methods:  GET

roles_new:
    path:     /new
    defaults: { _controller: "PylifeBundle:PlRole:new" }
    methods:  [GET, POST]

roles_edit:
    path:     /{id}/edit
    defaults: { _controller: "PylifeBundle:PlRole:edit" }
    methods:  [GET, POST]

roles_delete:
    path:     /{id}/delete
    defaults: { _controller: "PylifeBundle:PlRole:delete" }
    methods:  DELETE
