usuarios_index:
    path:     /
    defaults: { _controller: "PylifeBundle:PlUser:index" }
    methods:  GET

usuarios_show:
    path:     /{id}/show
    defaults: { _controller: "PylifeBundle:PlUser:show" }
    methods:  GET

usuarios_new:
    path:     /new
    defaults: { _controller: "PylifeBundle:PlUser:new" }
    methods:  [GET, POST]

usuarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "PylifeBundle:PlUser:edit" }
    methods:  [GET, POST]

usuarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "PylifeBundle:PlUser:delete" }
    methods:  DELETE
