PylifeBundle\Entity\PlRoleUser:
    type: entity
    table: pl_role_user
    indexes:
        fk_pl_user_pl_role_idx:
            columns:
                - ru_usr_id
        fk_pl_role_pl_role_user_idx:
            columns:
                - ru_rol_id
        fk_pl_user_pl_role_user_created_idx:
            columns:
                - ru_usr_created_by
        fk_pl_user_pl_role_user_updated_idx:
            columns:
                - ru_usr_updated_by
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ruCreatedAt:
            type: datetime
            nullable: false
            column: ru_created_at
        ruUpdatedAt:
            type: datetime
            nullable: true
            column: ru_updated_at
        ruActive:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: ru_active
    manyToOne:
        ruRol:
            targetEntity: PlRole
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ru_rol_id:
                    referencedColumnName: id
            orphanRemoval: false
        ruUsr:
            targetEntity: PlUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ru_usr_id:
                    referencedColumnName: id
            orphanRemoval: false
        ruUsrCreatedBy:
            targetEntity: PlUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ru_usr_created_by:
                    referencedColumnName: id
            orphanRemoval: false
        ruUsrUpdatedBy:
            targetEntity: PlUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ru_usr_updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
